services: 
  devcontainer:
  frontend:
    image: “ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main”
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./adapter:/source/adapter
    depends_on:
      - nginx
    ports:
      - "9080:9080" # Host port 9080 - Container port 9080
    command: sleep infinity # Keep container running

  nginx:
    image: nginx:latest
    ports:
      - "8080:80" # Host port 8080 - Container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Optional: custom config
    depends_on:
      - frontend # Ensure frontend is ready before starting nginx

    mongo:
      image: mongo
      ports:
        - "27017:27017" # Host port 27017 - Container port 27017
      container_name: mongo-db
      
    server:
      image: node:20
      working_dir: /app
      volumes:
        - ./:/app
      command: npx -y tsx ./index.ts
      ports:
        - "3000:3000" # Host port 3000 - Container port
      depends_on:
        - mongo # Ensure MongoDB is ready before starting the server
      container_name: server-app

    server2:
      image: node:20
      working_dir: /app
      volumes:
        - ./:/app
      command: npx -y tsx ./index.ts
      ports:
        - "3001:3000" # Host port 3001 - Container port 3000
      container_name: server-app-2
      
    server3:
      image: node:20
      working_dir: /app
      volumes:
        - ./:/app
      command: npx -y tsx ./index.ts
      ports:
        - "3002:3000" # Host port 3002 - Container port 3000
      container_name: server-app-3
